let autogeneratedUserId = 1000;
let autogeneratedBillId = 100;
let UserIdValue:User;

class ElectricBill
{
    BillId:string;
    BillPaid:number;
    DueDate:number;
    UserId:string;
    constructor(paramBillPaid:number,paramDueDate:number)
    {
        autogeneratedBillId++;
        this.BillId="EB"+autogeneratedBillId.toString();
        this.DueDate = paramDueDate;
        this.BillPaid = paramBillPaid;
    }
}
class User
{
    UserId:string;
    Name:string;
    MobileNumber:number;
    Address:string;
    Bill:Array<ElectricBill> =new Array<ElectricBill>();


    constructor(paramName:string, paramMobileNo:number,paramAddress:string)
    {
        autogeneratedUserId ++;
        this.UserId = "U"+autogeneratedUserId.toString();
        this.Name = paramName;
        this.MobileNumber = paramMobileNo;
        this.Address=paramAddress;
    }
}

let userDetail:Array<User> = new Array <User> ();

function loginPage()
{
    let login=document.getElementById("login") as HTMLDivElement;
    let home=document.getElementById("home") as HTMLDivElement;
    login.style.display="block";
    home.style.display="none";
}
function adminPage()
{
    let validPage=document.getElementById("adminPage") as HTMLDivElement;
    let home=document.getElementById("home") as HTMLDivElement;
    validPage.style.display="block";
    home.style.display="none";  
}
function option()
{

    let validPage=document.getElementById("validation") as HTMLDivElement;
    let optionPage=document.getElementById("option") as HTMLDivElement;
    optionPage.style.display="block";
    validPage.style.display="none";  
}

function register()
{
    let registerPage=document.getElementById("registerPage") as HTMLDivElement;
    let login=document.getElementById("login") as HTMLDivElement;
    registerPage.style.display="block";
    login.style.display="none"
}

function login()
{
    let optionPage=document.getElementById("option") as HTMLDivElement;
    let home=document.getElementById("home") as HTMLDivElement;
    let registerPage=document.getElementById("registerPage") as HTMLDivElement;
    registerPage.style.display="none"
    optionPage.style.display="none";
    home.style.display="block";   
}

function userLogin()
{
    let login=document.getElementById("login") as HTMLDivElement;
    let validPage=document.getElementById("validation") as HTMLDivElement;
    login.style.display="none";
    validPage.style.display="block";
}

function userPay()
{
    let pay=document.getElementById("pay") as HTMLDivElement;
    let optionPage=document.getElementById("option") as HTMLDivElement;
    optionPage.style.display="none";
    pay.style.display="block";
    for(let i=0;i<UserIdValue.Bill.length;i++)
    {
        let Billvalue = document.getElementById("billPay").innerHTML=(UserIdValue.Bill[i].BillPaid).toString();
        let Duevalue = document.getElementById("DueValuePay").innerHTML=(UserIdValue.Bill[i].DueDate).toString();
    }

}


function addNewUser()
{
    let Name=(document.getElementById("name") as HTMLInputElement).value;
    let PhoneNum=(document.getElementById("phoneNo") as HTMLInputElement).value;
    let Address = (document.getElementById("city") as HTMLInputElement).value;
    let obj = new User(Name,+PhoneNum,Address);
    userDetail.push(obj);
    alert("Hi....! " + obj.Name + " your user Id is " + obj.UserId);
}  

function billPage()
{
    let validPage=document.getElementById("adminPage") as HTMLDivElement; 
    let billPageInput=document.getElementById("billPage") as HTMLDivElement;
    validPage.style.display="none";
    billPageInput.style.display="block";
}

function billSubmit()
{
    let billPageInput=document.getElementById("billPage") as HTMLDivElement;
    billPageInput.style.display="none";
    let calculatedBill=document.getElementById("calculatedBill") as HTMLDivElement;
    calculatedBill.style.display="block";
    let PreviousUnit = (document.getElementById("prevUnit") as HTMLLIElement).value;
    let CurrentUnit = (document.getElementById("currUnit") as HTMLLIElement).value;
    let Date = (document.getElementById("date") as HTMLLIElement).value;
    let calculationPrice= (CurrentUnit-PreviousUnit)*5;
    let Billvalue = document.getElementById("bill").innerHTML= calculationPrice.toString();
    let  Duevalue= document.getElementById("DueValue").innerHTML= Date.toString();
    let billObj = new ElectricBill(calculationPrice,Date);
    UserIdValue.Bill.push(billObj); 
    alert("BillId is "+billObj.BillId +billObj.DueDate);
}
function userHistory()
{
    let optionPage=document.getElementById("option") as HTMLDivElement;
    optionPage.style.display="none";
    let historyPage=document.getElementById("historyPage") as HTMLDivElement;
    historyPage.style.display="block";
    for(let i=0;i<UserIdValue.Bill.length;i++)
    {
        let Billvalue = document.getElementById("userHistoryPage").innerHTML=(UserIdValue.Bill[i].BillPaid).toString();
        let Duevalue = document.getElementById("userDueDate").innerHTML=(UserIdValue.Bill[i].DueDate).toString();
        let userName = document.getElementById("userNameHistory").innerHTML=(UserIdValue.Name)
    }
}

function billToLogin()
{
    let calculatedBill=document.getElementById("calculatedBill") as HTMLDivElement;
    let home=document.getElementById("home") as HTMLDivElement;
    calculatedBill.style.display="none";
    home.style.display="block";

}

function adminLogin()
{
    let adminUserId=(document.getElementById("userIdAdmin") as HTMLInputElement).value;
    let flag=false;
    userDetail.forEach(element => 
        {
        if (element.UserId==adminUserId)
        {
            alert("Welcome for "+ element.Name +" login")
            billPage()
            flag=true;
        }
          
        }
        ); 
        if (flag==false)
        {
            alert("Wrong id ")
        }
    
}